In [1]:
3 + 5 * 4

23

In [2]:
weight_kg = 60

In [7]:
weight_kg_text = "weight in kilograms:"

In [8]:
print(weight_kg_text, weight_kg)

weight in kilograms: 60


In [9]:
print('Weight in pounds:',weight_kg *2.2)

Weight in pounds: 132.0


In [16]:
print(weight_kg)
weight_kg = weight_kg *3
print(weight_kg)
weight_kg = weight_kg +1

6210
18630


In [19]:
x = 5
y = 6


11
12


In [21]:
print(x+y)
x = y 
print(x+y)

12
12


In [22]:
mass = 47.5
age = 122
mass = mass * 5.0
age = age - 10
print(mass, age)

237.5 112


In [23]:
first, second = "Grace", "Shawn"
third, fourth = second, first
print(third, fourth)

Shawn Grace


In [25]:
import numpy 

numpy.loadtxt(fname="inflammation-01.csv", delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [27]:
medical_data = numpy.loadtxt(fname="inflammation-01.csv", delimiter=",")


print(medical_data)


[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [30]:
print(type(medical_data))
print(type(weight_kg))
print(type(weight_kg_text))

<class 'numpy.ndarray'>
<class 'int'>
<class 'str'>


In [31]:
print(medical_data.dtype)

float64


In [32]:
#rows, columns 
print(medical_data.shape)

(54, 40)


In [33]:
colors = ["red", "green", "blue"]

In [34]:
print(colors[0])

red


In [35]:
print('first value in medical data:', medical_data[0,0])

first value in medical data: 0.0


In [36]:
print('point in medical data', medical_data[30,20])

point in medical data 6.0


In [37]:
print(medical_data.shape)

(54, 40)


In [42]:
med_data_shape = medical_data.shape
print(med_data_shape[0])
print(med_data_shape[1])
middle_of_rows = int(med_data_shape[0]/2)
middle_of_cols = int(med_data_shape[1]/2)
print(middle_of_rows, middle_of_cols)

print('middle value of medical data:', medical_data[middle_of_rows, middle_of_cols])

54
40
27 20
middle value of medical data: 6.0


In [44]:
##slicing data
#print(medical_data[0:4, 0:10])


print(medical_data[5:10, 0:10])


[[0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [45]:
bruin = medical_data[:3, 36:]
print('bruin is:\n')
print(bruin)
#:3 is indexes 0,1,2
##36: is indexes 36,37, 38, 39

bruin is:

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [46]:
import numpy as np

In [47]:
import time
print(time.ctime())

Mon Jan 27 12:06:40 2020


In [48]:
meanval, stdval = np.mean(medical_data), np.std(medical_data)

In [50]:
print('mean',meanval,', standard deviation:', stdval)

mean 5.658333333333333 , standard deviation: 4.352194529455482


In [51]:
maxval, minval =np.max(medical_data), np.min(medical_data)
print('max:', maxval,', min:', minval)

max: 19.0 , min: 0.0


In [52]:
len(medical_data)

54

In [56]:
patient_1 = medical_data[0,:]
print(patient_1)
len(patient_1)
print(patient_1[1])

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]
0.0


In [58]:
max_infl_pt1 = np.max(patient_1)
print('max inflammation for patient 1:', max_infl_pt1) 

max inflammation for patient 1: 18.0


In [59]:
print('max inflammation for patient 2:' ,np.max(medical_data[1,:]))

max inflammation for patient 2: 18.0


In [60]:
print(np.max(medical_data, axis=1))

[18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.
 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.
 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.]


In [61]:
print(np.max(medical_data, axis=0))

[ 0.  1.  2.  3.  3.  2.  6.  7.  8.  9. 10. 11. 10.  9.  7. 15.  7. 16.
 12. 18. 19. 14. 12. 17. 12. 12. 11.  7. 11.  8. 10.  5.  5.  7.  5.  5.
  2.  3.  1.  1.]


In [64]:
def hello_person(name, friend):
    print("Hello", name, ", and your friend", friend, "too!")

In [65]:
hello_person("Eric", "Steven")

Hello Eric , and your friend Steven too!


In [70]:
def square_numbers(x):
    return(x*x)

In [71]:
sq1 = square_numbers(5)

In [72]:
print(sq1)

25


In [75]:
5**3

def pp(base, exponent):
    return(base**exponent)

In [76]:
pp(5,2)

25

In [77]:
pp(50,3)

125000